### ISSUE TITLE
Module no longer compatible with Drupal 9.2.7

### ISSUE THREAD

**Issue by yonailo** [Lullabot/block_dashboard#4]
It seems this module is not compatible with D9, could you please update it ?

**Comment by deviantintegral** [comment]
@karens , @mrdavidburns do you know if we're still using this on any current projects?

@yonailo Feel free to open a pull request. If it turns out we're not actively using this anymore, we'd be glad to archive this repo and point it to a drupal.org project if you would like to take on ownership.

**Comment by mrdavidburns** [comment]
I just searched all the LSM projects and the only one where it exists is Lullabot.com.
https://github.com/Lullabot/lullabot.com-d8/tree/main/web/modules/github/block_dashboard
https://github.com/Lullabot/lullabot.com-d8/blob/main/files/config/sync/core.extension.yml#L13

**Comment by deviantintegral** [comment]
Ok, given it's there unless we plan on removing it I assume we'll get it updated.
